version: '3'

services:
  sp1_prover:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
    volumes:
      - ./data:/app/data
    restart: unless-stopped
