[phases.setup]
nixPkgs = ["gcc", "pkg-config", "openssl", "openssl.dev", "rustup", "cargo"]
cmds = [
  "rustup default stable"
]

[phases.build]
cmds = []

[start]
cmd = ""

[variables]
CARGO_NET_GIT_FETCH_WITH_CLI = "true"
CARGO_REGISTRIES_CRATES_IO_PROTOCOL = "sparse"
PATH = "/root/.cargo/bin:${PATH}"

[nixpacks]
plan_path = "/tmp/nixpacks/plan.json"

[phases.build.cache]
directories = ["target", "/root/.cargo"]

[phases.build.nixpkgs]
collect_output = true

[phases.build.nixpkgs.opts]
cores = 4
memory = "8GB" 