[build]
builder = "NIXPACKS"
buildCommand = "cargo build --release"

[deploy]
startCommand = "./target/release/sudoku_backend"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
PORT = "3000" 