[build]
builder = "nixpacks"
buildCommand = "RUSTFLAGS=\"-C codegen-units=1 -C opt-level=z\" cargo build --release"

[deploy]
startCommand = "RUST_LOG=info ./target/release/sudoku_backend"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[variables]
PORT = "8080"
CARGO_NET_GIT_FETCH_WITH_CLI = "true" 