[build]
builder = "nixpacks"
buildCommand = "./build.sh"
watchPatterns = ["src/**/*.rs", "Cargo.toml", "Cargo.lock"]
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "RUST_LOG=info ./target/release/sudoku_backend"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[variables]
PORT = "8080" 