[build]
builder = "nixpacks"
buildCommand = "cargo build --release"

[deploy]
startCommand = "RUST_LOG=info ./target/release/sudoku_backend"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"

[variables]
PORT = "3000" 