[build]
rustflags = ["-C", "link-arg=-s", "-C", "codegen-units=16", "-C", "debuginfo=0", "-C", "opt-level=z"]

[profile.dev]
incremental = true
debug = 0

[profile.release]
incremental = true
debug = 0
codegen-units = 16
opt-level = "z"
lto = "thin"
strip = true

[net]
git-fetch-with-cli = true

[registries.crates-io]
protocol = "sparse" 